name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: rust-rustfmt-check
      uses: mbrobbel/rustfmt-check@0.3.0
    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --verbose
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
          command: test
          args: --verbose
